server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metadb?serverTimezone=UTC
    username: metamong
    password: metamong
  config:
    import: application-sms.yml

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  properties:
    hibernate:
      format_sql: true
      show_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}